version: "3"

# ===== SERVICES =====

services:

  # ===== web app =====

  app:
    container_name: app
    build:
      dockerfile: Dockerfile
    networks:
      - network-global
    depends_on:
      - mongo_ingestion
    ports:
      - 8080:8080



  # ===== mongo ingestion =====

  mongo_ingestion:
    container_name: mongo_ingestion
    build:
      dockerfile: data/Dockerfile
    networks:
      - network-global
    volumes:
      - mongodbdata:/data/db

# ===== NETWORKS =====
networks:
  network-global:
    driver: bridge

# ===== Volumes =====
volumes:
  mongodbdata:
    driver: local






